const genreOptions = [
    {"id":2,"name":"Point-and-click"},
    {"id":4,"name":"Fighting"},
    {"id":5,"name":"Shooter"},
    {"id":7,"name":"Music"},
    {"id":8,"name":"Platform"},
    {"id":9,"name":"Puzzle"},
    {"id":10,"name":"Racing"},
    {"id":11,"name":"Real Time Strategy (RTS)"},
    {"id":12,"name":"Role-playing (RPG)"},
    {"id":13,"name":"Simulator"},
    {"id":14,"name":"Sport"},
    {"id":15,"name":"Strategy"},
    {"id":16,"name":"Turn-based strategy (TBS)"},
    {"id":24,"name":"Tactical"},
    {"id":25,"name":"Hack and slash/Beat 'em up"},
    {"id":26,"name":"Quiz/Trivia"},
    {"id":30,"name":"Pinball"},
    {"id":31,"name":"Adventure"},
    {"id":32,"name":"Indie"},
    {"id":33,"name":"Arcade"},
    {"id":34,"name":"Visual Novel"},
    {"id":35,"name":"Card & Board Game"},
    {"id":36,"name":"MOBA"}
];

const yearOptions = [
    {
        id: 0,
        name: "All years",
        date: {
            start: null,
            end: null,
        },
    },
    {
        id: 1,
        name: "Pre-70s",
        date: {
            start: -2208988800,
            end: -1,
        },
    },
    {
        id: 2,
        name: "70s",
        date: {
            start: 0,
            end: 315532799,
        },
    },
    {
        id: 3,
        name: "80s",
        date: {
            start: 315532800,
            end: 631151999,
        },
    },
    {
        id: 4,
        name: "90s",
        date: {
            start: 631152000,
            end: 946684799,
        },
    },
    {
        id: 5,
        name: "2000s",
        date: {
            start: 946684800,
            end: 1262303999,
        },
    },
    {
        id: 6,
        name: "2010s",
        date: {
            start: 1262304000,
            end: 1577836799,
        },
    },
    {
        id: 7,
        name: "2020 and newer",
        date: {
            start: 1577836800,
            end: null,
        },
    },
]

const consoleOptions = [
    {"id":376,"name":"Epoch Super Cassette Vision"},
    {"id":12,"name":"Xbox 360"},
    {"id":32,"name":"Sega Saturn"},
    {"id":62,"name":"Atari Jaguar"},
    {"id":148,"name":"AY-3-8607"},
    {"id":306,"name":"Satellaview"},
    {"id":339,"name":"Sega Pico"},
    {"id":60,"name":"Atari 7800"},
    {"id":41,"name":"Wii U"},
    {"id":506,"name":"Amstrad GX4000"},
    {"id":410,"name":"Atari Jaguar CD"},
    {"id":30,"name":"Sega 32X"},
    {"id":127,"name":"Fairchild Channel F"},
    {"id":143,"name":"AY-3-8760"},
    {"id":167,"name":"PlayStation 5"},
    {"id":70,"name":"Vectrex"},
    {"id":87,"name":"Virtual Boy"},
    {"id":145,"name":"AY-3-8603"},
    {"id":386,"name":"Meta Quest 2"},
    {"id":390,"name":"PlayStation VR2"},
    {"id":165,"name":"PlayStation VR"},
    {"id":504,"name":"Uzebox"},
    {"id":473,"name":"Arcadia 2001"},
    {"id":48,"name":"PlayStation 4"},
    {"id":51,"name":"Family Computer Disk System"},
    {"id":128,"name":"PC Engine SuperGrafx"},
    {"id":482,"name":"Sega CD 32X"},
    {"id":8,"name":"PlayStation 2"},
    {"id":88,"name":"Odyssey"},
    {"id":23,"name":"Dreamcast"},
    {"id":136,"name":"Neo Geo CD"},
    {"id":78,"name":"Sega CD"},
    {"id":144,"name":"AY-3-8710"},
    {"id":146,"name":"AY-3-8605"},
    {"id":147,"name":"AY-3-8606"},
    {"id":72,"name":"Ouya"},
    {"id":142,"name":"PC-50X Family"},
    {"id":9,"name":"PlayStation 3"},
    {"id":11,"name":"Xbox"},
    {"id":18,"name":"Nintendo Entertainment System"},
    {"id":308,"name":"Playdia"},
    {"id":117,"name":"Philips CD-i"},
    {"id":67,"name":"Intellivision"},
    {"id":86,"name":"TurboGrafx-16/PC Engine"},
    {"id":66,"name":"Atari 5200"},
    {"id":131,"name":"Super NES CD-ROM System"},
    {"id":138,"name":"VC 4000"},
    {"id":139,"name":"1292 Advanced Programmable Video System"},
    {"id":114,"name":"Amiga CD32"},
    {"id":375,"name":"Epoch Cassette Vision"},
    {"id":382,"name":"Intellivision Amico"},
    {"id":384,"name":"Oculus Quest"},
    {"id":385,"name":"Oculus Rift"},
    {"id":387,"name":"Oculus Go"},
    {"id":479,"name":"Terebikko / See 'n Say Video Phone"},
    {"id":507,"name":"Advanced Pico Beena"},
    {"id":508,"name":"Nintendo Switch 2"},
    {"id":21,"name":"Nintendo GameCube"},
    {"id":80,"name":"Neo Geo AES"},
    {"id":84,"name":"SG-1000"},
    {"id":91,"name":"Bally Astrocade"},
    {"id":122,"name":"Nuon"},
    {"id":388,"name":"Gear VR"},
    {"id":380,"name":"Casio Loopy"},
    {"id":478,"name":"Panasonic M2"},
    {"id":509,"name":"Polymega"},
    {"id":169,"name":"Xbox Series X|S"},
    {"id":64,"name":"Sega Master System/Mark III"},
    {"id":99,"name":"Family Computer"},
    {"id":50,"name":"3DO Interactive Multiplayer"},
    {"id":238,"name":"DVD Player"},
    {"id":239,"name":"Blu-ray Player"},
    {"id":240,"name":"Zeebo"},
    {"id":274,"name":"PC-FX"},
    {"id":407,"name":"HyperScan"},
    {"id":414,"name":"LeapTV"},
    {"id":439,"name":"V.Smile"},
    {"id":471,"name":"Meta Quest 3"},
    {"id":476,"name":"Apple Pippin"},
    {"id":480,"name":"Super A'Can"},
    {"id":7,"name":"PlayStation"},
    {"id":68,"name":"ColecoVision"},
    {"id":29,"name":"Sega Mega Drive/Genesis"},
    {"id":416,"name":"64DD"},
    {"id":59,"name":"Atari 2600"},
    {"id":130,"name":"Nintendo Switch"},
    {"id":487,"name":"LaserActive"},
    {"id":4,"name":"Nintendo 64"},
    {"id":5,"name":"Wii"},
    {"id":19,"name":"Super Nintendo Entertainment System"},
    {"id":49,"name":"Xbox One"},
    {"id":58,"name":"Super Famicom"}
]

export {genreOptions, yearOptions, consoleOptions}